services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

  spark:
    image: apache/spark:3.5.1
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
